triangles_mesh_path: './jupyter_nb/full_sparse_bunny.ply'
#triangles_mesh_path: '/home/mhyip/Works/07_extract_mbes/mbes_data/airplane/airplane_bpa.ply'

hole_detection:
  calculate_relation: True
  show_singular_vertices: True

visualizer: 
  show_all_boundaries: False
  show_relations: True